import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer1 from "@/components/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  return (
    <html lang="en" dir='rtl'  >
      <body className='bg-white text-black flex flex-col mx-auto'>
      <Navbar/>
        {children}
      <Footer1/>
      </body>
    </html>
  );
}
